Repository cryptpad/cryptpad, pull requests merged in 2023-07, with the labels that each got.

#1067 add a "make a copy" element to onlyoffice applications
  www/common/onlyoffice/inner.js
Labels: Spreadsheet, Document, Presentation, UI/UX

#1068 fix issue #1054 by converting png to ico and linking them
  customize.dist/favicon.ico
  customize.dist/favicon/alt-favicon-code.ico
  customize.dist/favicon/alt-favicon-doc.ico
  customize.dist/favicon/alt-favicon-form.ico
  customize.dist/favicon/alt-favicon-kanban.ico
  customize.dist/favicon/alt-favicon-pad.ico
  customize.dist/favicon/alt-favicon-poll.ico
  customize.dist/favicon/alt-favicon-presentation.ico
  customize.dist/favicon/alt-favicon-sheet.ico
  customize.dist/favicon/alt-favicon-slide.ico
  customize.dist/favicon/alt-favicon-whiteboard.ico
  customize.dist/favicon/alt-favicon.ico
  customize.dist/favicon/main-favicon-code.ico
  customize.dist/favicon/main-favicon-doc.ico
  customize.dist/favicon/main-favicon-form.ico
  customize.dist/favicon/main-favicon-kanban.ico
  customize.dist/favicon/main-favicon-pad.ico
  customize.dist/favicon/main-favicon-poll.ico
  customize.dist/favicon/main-favicon-presentation.ico
  customize.dist/favicon/main-favicon-sheet.ico
  customize.dist/favicon/main-favicon-slide.ico
  customize.dist/favicon/main-favicon-teams.ico
  customize.dist/favicon/main-favicon-whiteboard.ico
  customize.dist/favicon/main-favicon.ico
  www/code/index.html
  www/common/notify.js
  www/doc/index.html
  www/form/index.html
  www/kanban/index.html
  www/pad/index.html
  www/poll/index.html
  www/presentation/index.html
  www/sheet/index.html
  www/slide/index.html
  www/teams/index.html
  www/whiteboard/index.html
Labels: UI/UX

#1075 add " (copy)" to copied OpenOffice files
  www/common/onlyoffice/inner.js
Labels: Spreadsheet, Document, Presentation, UI/UX

#1064 Merge back Docker inside the main repository
  .dockerignore
  .github/workflows/publish-release.yml
  .github/workflows/publish.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
  readme.md
Labels: Deployment

#1154 remove unnecessary right padding from all lists in Rich Text(pad)
  customize.dist/ckeditor-contents.css
Labels: Rich Text, UI/UX
