Repository cryptpad/cryptpad, pull requests merged in 2023-09, with the labels that each got.

#1229 Uncommented button styling
  customize.dist/src/less2/include/sidebar-layout.less
Labels: UI/UX

#1252 Localize online status in generated account report
  www/admin/inner.js
Labels: Internationalization

#1113 add even space between category buttons
  customize.dist/src/less2/include/sidebar-layout.less
Labels: Mobile support, UI/UX

#1222 Fix emoji avatars not displayed consistently
  www/calendar/inner.js
  www/common/inner/access.js
Labels: UI/UX

#1078 add vertical padding to Kanban card container
  www/kanban/app-kanban.less
Labels: Kanban, UI/UX
