Repository cryptpad/cryptpad, pull requests merged in 2024-12, with the labels that each got.

#1706 Change iframe title
  www/common/sframe-common-outer.js
Labels: Accessibility, OK to Merge, Screen Reader

#1672 Fix keyboard trap inside Form description
  www/form/inner.js
Labels: Accessibility, Form, HAN scan 08-24, Keyboard navigation

#1669 Disable arrow key navigation in the drive while modal is active
  www/common/common-ui-elements.js
  www/common/drive-ui.js
Labels: Accessibility

#1726 Simulate click action for keyboard users in Ctrl+E modal
  www/common/drive-ui.js
Labels: Accessibility, Ready to Test, Keyboard navigation

#1697 Prevent links in trash from disappearing after drive reload
  www/common/outer/userObject.js
Labels: OK to Merge

#1682 Fix spacing issues in Forms
  www/form/app-form.less
  www/form/inner.js
Labels: Accessibility, Form, UI/UX, Ready to Review

#1688 No Notifications padding issue
  customize.dist/src/less2/include/toolbar.less
Labels: Ready to Review

#1723 Fix some form storage-related bugs
  www/common/cryptpad-common.js
  www/form/templates.js
Labels: Bug, Form, UI/UX, Ready to Test

#1681 Stops selection of all other trashed files when restoring single file
  www/common/drive-ui.js
Labels: Bug, Drive, UI/UX, Ready to Test

#1674 Notification fixes
  customize.dist/src/less2/include/dropdown.less
  customize.dist/src/less2/include/notifications.less
  www/common/sframe-common-mailbox.js
  www/common/toolbar.js
Labels: Accessibility, UI/UX, Ready to Test, Keyboard navigation

#1695 Links included in Drive exports
  www/common/make-backup.js
Labels: Drive, Ready to Test

#1680 'Request edit' button
  www/common/inner/access.js
  www/common/inner/common-modal.js
Labels: Bug, Ready to Test

#1690 Form password warning
  customize.dist/messages.js
  customize.dist/src/less2/include/creation.less
  www/common/common-ui-elements.js
Labels: Ready to Test

#1584 Enable toggle in and out of calendars on small screens
  customize.dist/messages.js
  www/calendar/app-calendar.less
  www/calendar/inner.js
  www/common/outer/calendar.js
Labels: Ready to Test

#1691 Weblate translations for 2024.12 release
  www/common/translations/messages.bg.json
  www/common/translations/messages.de.json
  www/common/translations/messages.fr.json
  www/common/translations/messages.hu.json
  www/common/translations/messages.it.json
  www/common/translations/messages.json
  www/common/translations/messages.nl.json
  www/common/translations/messages.pl.json
  www/common/translations/messages.tr.json
  www/common/translations/messages.zh.json
Labels: Internationalization, Ready to Review
