Repository cryptpad/cryptpad, pull requests merged in 2024-09, with the labels that each got.

#1614 Team roster channels slow down team members accounts
  customize.dist/messages.js
  www/common/outer/history.js
  www/common/outer/roster.js
  www/report/main.js
  www/teams/app-team.less
  www/teams/inner.js
Labels: Ready to Test

#1569 Make password change confirmation button responsive on mobile
  customize.dist/src/less2/include/forms.less
  customize.dist/src/less2/pages/page-install.less
  customize.dist/src/less2/pages/page-register.less
  www/calendar/app-calendar.less
  www/common/common-interface.js
  www/install/main.js
  www/register/main.js
  www/settings/app-settings.less
  www/settings/inner.js
Labels: Ready to Test

#1583 Make 'New Event' modal appear in user view for small screens
  www/calendar/app-calendar.less
Labels: Ready to Test

#1586 Make code history buttons not overlap on small screens
  customize.dist/src/less2/include/toolbar-history.less
Labels: Ready to Test

#1610 `+New` button fixes on Drive
  www/common/drive-ui.js
Labels: Accessibility, Ready to Test

#1615 Calendar modal UI fixes
  www/calendar/app-calendar.less
  www/common/common-ui-elements.js
Labels: UI/UX, Ready to Test

#1605 Missing margin on Features page
  customize.dist/pages/features.js
  customize.dist/src/less2/pages/page-features.less
Labels: Ready to Test

#1611 Drive focus fixes
  www/drive/inner.html
Labels: Accessibility, Ready to Test

#1560 Focus style fixes
  customize.dist/pages/features.js
  customize.dist/pages/index.js
  customize.dist/src/less2/include/alertify.less
  customize.dist/src/less2/include/checkmark.less
  customize.dist/src/less2/include/drive.less
  customize.dist/src/less2/include/forms.less
  customize.dist/src/less2/include/infopages.less
  customize.dist/src/less2/include/sidebar-layout.less
  customize.dist/src/less2/include/tokenfield.less
  customize.dist/src/less2/include/toolbar.less
  customize.dist/src/less2/include/variables.less
  customize.dist/src/less2/pages/page-features.less
  customize.dist/src/less2/pages/page-index.less
  www/admin/app-admin.less
  www/calendar/app-calendar.less
  www/kanban/app-kanban.less
  www/settings/app-settings.less
  www/teams/app-team.less
Labels: Accessibility, Ready to Test

#1647 `Shift-Tab` option for `Ctrl-E` modals
  www/common/common-ui-elements.js
Labels: Accessibility, Ready to Review

#1616 Weblate translations as of 2024-09-03
  www/common/translations/messages.bg.json
  www/common/translations/messages.ca.json
  www/common/translations/messages.da.json
  www/common/translations/messages.es.json
  www/common/translations/messages.es_CU.json
  www/common/translations/messages.eu.json
  www/common/translations/messages.fr.json
  www/common/translations/messages.it.json
  www/common/translations/messages.ja.json
  www/common/translations/messages.json
  www/common/translations/messages.pl.json
  www/common/translations/messages.ro.json
  www/common/translations/messages.ru.json
Labels: Internationalization, Ready to Review

#1655 Fix calendar ownership sharing bug
  www/common/inner/common-modal.js
Labels: Bug, Calendar, Ready to Review
