Repository cryptpad/cryptpad, pull requests merged in 2024-06, with the labels that each got.

#1464 #1089: Fix contextual menu `Open` on anonymous drive
  www/common/drive-ui.js
Labels: Bug, Drive

#1466 #1465: unsharp the corners when hovering the dismiss button on notification dropdown menu
  customize.dist/src/less2/include/notifications.less
Labels: UI/UX

#1473 Fix locked focus on text editors
  customize.dist/src/less2/include/toolbar.less
  www/common/sframe-common-codemirror.js
Labels: Accessibility

#844 Remove mediatag subfolder - see issue #843
  www/mediatag/index.html
  www/mediatag/main.js
  www/mediatag/media-tag.js
Labels: Dependencies

#1470 Accessibility fixes
  customize.dist/messages.js
  www/admin/inner.js
  www/common/common-interface.js
  www/common/common-ui-elements.js
  www/common/drive-ui.js
  www/common/sframe-common-outer.js
  www/common/toolbar.js
  www/teams/inner.js
Labels: Accessibility

#1488 Kanban accessibility fixes
  www/kanban/app-kanban.less
  www/kanban/inner.js
  www/kanban/jkanban_cp.js
Labels: Kanban, Accessibility
