Repository cryptpad/cryptpad, pull requests merged in 2025-03, with the labels that each got.

#1800 Blob metadata refactoring
  lib/api.js
  lib/archive-account.js
  lib/commands/admin-rpc.js
  lib/commands/metadata.js
  lib/decrees.js
  lib/env.js
  lib/eviction.js
  lib/hk-util.js
  lib/pins.js
  lib/storage/blob.js
  lib/workers/db-worker.js
  lib/workers/index.js
  scripts/migrations/migrate-blob-proofs.js
  scripts/user-statistics.js
  server.js
Labels: Ready to Test

#1801 Add and remove admins from the UI
  customize.dist/messages.js
  customize.dist/src/less2/include/sidebar-layout.less
  lib/commands/admin-rpc.js
  lib/decrees-core.js
  lib/decrees.js
  lib/env.js
  lib/http-worker.js
  lib/load-config.js
  package-lock.json
  package.json
  www/admin/app-admin.less
  www/admin/inner.js
  www/common/inner/sidebar-layout.js
Labels: Ready to Test

#1820 New OnlyOffice default config options
  www/common/onlyoffice/inner.js
  www/common/sframe-boot2.js
Labels: Ready to Test

#1816 Fix kanban cursor issues when editing collaboratively
  www/kanban/inner.js
Labels: Ready to Test

#1812 Kanban "See all tags" button fix
  customize.dist/src/less2/include/colortheme-dark.less
  customize.dist/src/less2/include/colortheme.less
  customize.dist/src/less2/include/forms.less
  www/kanban/app-kanban.less
  www/kanban/inner.js
Labels: Ready to Test

#1797 Integration API
  customize.dist/messages.js
  lib/historyKeeper.js
  lib/hk-util.js
  package-lock.json
  package.json
  www/common/onlyoffice/inner.js
  www/common/outer/async-store.js
  www/common/sframe-app-outer.js
  www/common/sframe-common-outer.js
  www/cryptpad-api.js
  www/integration/main.js
Labels: Ready to Test

#1739 Sort files and folders with "natural" sort
  www/common/drive-ui.js
Labels: Ready to Test

#1784 Fix anonymous drive download
  www/common/drive-ui.js
  www/common/make-backup.js
  www/common/userObject.js
  www/settings/inner.js
Labels: Ready to Test

#1774 Add Skip Link
  customize.dist/messages.js
  customize.dist/src/less2/include/toolbar.less
  www/admin/inner.js
  www/calendar/inner.js
  www/code/inner.js
  www/common/onlyoffice/inner.js
  www/common/sframe-app-framework.js
  www/common/toolbar.js
  www/diagram/inner.js
  www/drive/inner.js
  www/form/inner.js
  www/kanban/inner.js
  www/notifications/inner.js
  www/pad/inner.js
  www/profile/inner.js
  www/settings/inner.js
  www/slide/inner.js
  www/teams/inner.js
  www/whiteboard/inner.js
Labels: Ready to Test

#1780 Notifications sidebar: Fix keyboard navigation issues
  www/notifications/inner.js
Labels: Ready to Test

#1802 Enable keyboard usage for "Add Item" buttons in Kanban
  customize.dist/messages.js
  www/kanban/jkanban_cp.js
Labels: Ready to Test

#1752 Treat relative URLs in the sandbox as relative to the outer domain
  www/common/sframe-common.js
Labels: Ready to Test

#1829 Accessibility fixes to Admin UI
  customize.dist/messages.js
  www/admin/inner.js
  www/common/inner/sidebar-layout.js
Labels: Ready to Review

#1755 Improved calendar dropdown: keyboard accessibility and title overflow fixes
  www/calendar/app-calendar.less
  www/calendar/inner.js
Labels: Ready to Test

#1789 Add descriptive error messages
  customize.dist/messages.js
  www/admin/inner.js
  www/form/inner.js
  www/settings/inner.js
Labels: Ready to Test

#1753 Buttons for moving question blocks in Forms (mobile)
  customize.dist/messages.js
  www/form/app-form.less
  www/form/inner.js
Labels: Ready to Review, Ready to Test

#1711 Form answers Drive download
  www/common/cryptpad-common.js
  www/common/make-backup.js
  www/common/sframe-common-outer.js
  www/common/userObject.js
  www/form/command-handler.js
  www/form/export.js
  www/form/main.js
Labels: Ready to Test

#1775 Prevent saving file to Drive multiple times
  www/common/common-ui-elements.js
  www/common/outer/async-store.js
Labels: Ready to Test

#1759 Enable preview mode on mobile code app
  www/code/app-code.less
  www/code/inner.js
  www/common/common-ui-elements.js
Labels: Ready to Test

#1747 Fix long question text overflow and weird sizing of the required label in forms
  www/form/app-form.less
Labels: Ready to Test

#1799 Weblate translations for 2025.3.0 release
  www/common/translations/messages.bg.json
  www/common/translations/messages.ca.json
  www/common/translations/messages.cs.json
  www/common/translations/messages.da.json
  www/common/translations/messages.es.json
  www/common/translations/messages.eu.json
  www/common/translations/messages.it.json
  www/common/translations/messages.json
  www/common/translations/messages.nl.json
  www/common/translations/messages.pt-br.json
  www/common/translations/messages.ro.json
  www/common/translations/messages.ru.json
  www/common/translations/messages.sk.json
  www/common/translations/messages.zh.json
Labels: Internationalization
