Repository cryptpad/cryptpad, pull requests merged in 2025-06, with the labels that each got.

#1869 Update contact page
  SECURITY.md
  customize.dist/contact.html
  customize.dist/images/forum.svg
  customize.dist/images/forum.svg.license
  customize.dist/images/irc.svg
  customize.dist/images/irc.svg.license
  customize.dist/images/issue.svg
  customize.dist/images/issue.svg.license
  customize.dist/images/twiitter.svg
  customize.dist/images/twiitter.svg.license
  customize.dist/messages.js
  customize.dist/pages/contact.js
  readme.md
Labels: UI/UX, Ready to Test

#1926 Can exit presentation mode on mobile
  www/slide/slide.js
Labels: Markdown slides, Ready to Test

#1845 Make text area markdown toolbar responsive
  customize.dist/messages.js
  customize.dist/src/less2/include/markdown.less
  customize.dist/src/less2/include/toolbar.less
  www/code/inner.js
  www/common/common-ui-elements.js
  www/form/app-form.less
  www/form/inner.js
  www/kanban/app-kanban.less
  www/kanban/inner.js
  www/profile/app-profile.less
  www/profile/inner.js
Labels: Ready to Test

#1847 Documentation notification can be dismissed via keyboard
  customize.dist/messages.js
  customize.dist/src/less2/include/help.less
  www/common/common-ui-elements.js
Labels: Ready to Test

#1866 Fix diagram export
  www/diagram/export.js
Labels: Diagram, Ready to Test

#1906 Diagram history
  www/diagram/inner.js
Labels: Ready to Test

#1846 Improve Kanban Tags accessibility with keyboard navigation
  www/kanban/app-kanban.less
  www/kanban/inner.js
Labels: Ready to Test

#1848 Improve notification page accessibility, responsiveness and UI
  customize.dist/messages.js
  www/common/common-ui-elements.js
  www/common/sframe-common-mailbox.js
  www/common/toolbar.js
  www/notifications/app-notifications.less
  www/notifications/inner.js
Labels: Ready to Test

#1936 Fix missing recurring calendar after update
  src/common/recurrence.js
  www/calendar/inner.js
Labels: Ready to Test
